services:
  db:
      container_name: example-db
      image: postgres:16.4
      restart: always
      ports:
        - "5432:5432"
      networks:
        - example
      volumes:
        - ./db-data:/var/lib/postgresql/data
      env_file:
        - .env
      healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
        interval: 5s
        timeout: 5s
        retries: 5
  api:
      container_name: example-api
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8080:8080
      networks:
        - example
      depends_on:
        db:
          condition: service_healthy
      env_file:
        - .env
networks:
  example: