services:
  db:
      image: postgres:16.4
      restart: always
      ports:
        - "5432:5432"
      networks:
        - example
      volumes:
        - ./db-data:/var/lib/postgresql/data
      env_file:
        - .env
networks:
  example: